### ISSUE TITLE
Data API Python 範例錯誤

### ISSUE THREAD

**Issue by JJJHANG** [depositar/ckanext-data-depositario#18]
![Screenshot 2024-05-09 at 3 29 22 PM](https://github.com/depositar/ckanext-data-depositario/assets/97888861/02870ac4-f75a-4e17-824e-5b1cd3802c46)

Data API 提供的 Python 範例如上圖，有兩個錯誤：

1.  套件用法：在Python 3.x中，urllib已被分成urllib.request和urllib.error等子模組。
2. 函數用法：print fileobj.read() 應改為 print(fileobj.read())

測試過後，改用以下程式碼可以正常 query 且 print 出結果
```Python
import urllib.request
import urllib.parse

url = 'https://data.depositar.io/zh_Hant_TW/api/3/action/datastore_search?resource_id=064fee19-9eaf-4d9c-aa19-35d627b22785&limit=5&q=柚子湖秘境瀑布'
url = urllib.parse.quote(url, safe=':/?=&')  # 有中文查詢時，將非ASCII字符進行URL編碼
fileobj = urllib.request.urlopen(url)
print(fileobj.read())
```

**Comment by u10313335** [comment]
感謝回報。

此部分涉及 CKAN 核心程式。
目前已有相關 PR (ckan/ckan#7578) 處理此問題，但尚未有具體併入新版的時程。
在 CKAN 更新之前，仍會維持現有的 Python 2 範例。不便之處敬請見諒。
