### ISSUE TITLE
顯示 資料與資源的檔案描述過長時會被檔住

### ISSUE THREAD

**Issue by allycat** [depositar/ckanext-data-depositario#3]
ex: https://data.depositar.io/dataset/tw_taichung_salu_nsr_20180602

檔案描述較長的話，會被「探索」按述檔住 。
小問題，不急，網站上新的檔案上傳 ，點一點看到的。
PS: 在 firefox & chrome 都有

**Comment by u10313335** [comment]
這應該是 CKAN 核心本來就存在的問題，有空再來研究。

**Comment by allycat** [comment]
看是不是之後更新就一起好了。 XD 到時再關掉。

**Comment by u10313335** [comment]
先前客製化介面將行高調整為 30px 後，此問題即被修正。請參考以下程式碼片段。

https://github.com/depositar/ckanext-data-depositario/blob/877ac3296aea31ffa87214b75422deaba2413f56/ckanext/data_depositario/fanstatic/styles/custom.css#L57
