### ISSUE TITLE
Dataset  CSV 預覽時，顯示總共有多少筆數錯誤

### ISSUE THREAD

**Issue by allycat** [depositar/ckanext-data-depositario#4]

**Comment by u10313335** [comment]
請提供

* 範例
* 預期行為
* 實際行為

以便排查，謝謝！

**Comment by allycat** [comment]
範列
https://data.depositar.io/dataset/68f83/resource/1a398302-e48a-47aa-b3b1-da0b9cbf9050

預覽表格旁上寫 1000 records ，應是總筆數，預期會顯示該csv 共一萬七千多筆，但只顯示1000recods

若為該頁顯示的筆數，亦不對，一頁目前是顯示100筆，而非1000筆。

可顯示為 共xxx筆，本頁顯示xxx筆。（參考）
較清楚了解的是總筆數還是單頁筆數。

**Comment by u10313335** [comment]
感謝 @allycat 提供範例。

初步檢查後，之所以顯示為 1,000 筆，是由於上次上傳時僅完成 1,000 筆 records 就發生錯誤，我再進入資源管理頁面下的「DataStore」頁籤重新上傳一次就正常了。

目前看起來 [DataPusher](https://docs.ckan.org/projects/datapusher/) 套件 (負責將 CSV 儲存至 DataStore 資料庫) 與 DataStore 的連線似乎不太穩定。我後續再進行詳細調查。

因為不是顯示筆數錯誤的問題，我就先將這個 issue 關閉了。

**Comment by chengh42** [comment]
Hi 你好！很感謝 depositar 團隊營運與維護這個平台，我近日在使用平台時似乎也遇到了類似的狀況：

### 預期行為

範例：https://data.depositar.io/zh_TW/dataset/company-general/resource/1687dd76-23dd-4921-869f-2ea98154423f

- 資料瀏覽器上所顯示的資料筆數應與所上傳檔案相同
- 資料 API 可存取所有上傳檔案內的資料

### 實際行為

- 所上傳的 csv 檔應有1500多筆資料，但在資料瀏覽器顯示為 1000 records （見下方截圖）
- 點選下載後得到的 csv 檔，開啟查看後確實有1500多筆資料
- 使用資料 API 時，offset > 1000 即無資料：https://data.depositar.io/zh_TW/api/3/action/datastore_search?resource_id=1687dd76-23dd-4921-869f-2ea98154423f&limit=5&offset=1000

cc @qyke

![image](https://user-images.githubusercontent.com/44002425/125574595-f9c0e087-0c7e-48a9-b2c2-370bc2f0f637.png)

**Comment by u10313335** [comment]
感謝 @chengh42 的回報，此問題已另外開立 issue：#11

從資料 API 的[上傳後台](https://data.depositar.io/zh_TW/dataset/company-general/resource_data/1687dd76-23dd-4921-869f-2ea98154423f) (需登入) 可以看到 HTTP status code: 409 的錯誤。

初步判斷此問題與核心套件 (CKAN) 有關，但尚未修復。

我們也會嘗試處理，抱歉造成您使用上的不便。

**Comment by u10313335** [comment]
@chengh42 您好，

經排查後，發現 CKAN 所使用的結構化資料處理套件 DataPusher，會以表格的頭幾行資料內容來判定表格的欄位類型 (如：數字、文字等)。
然而，只要後面行數的內容類型與頭幾行不同 (您的資料屬於此情形)，將可能因類型不一致而發生錯誤，導致上傳中斷。

在 depositar 的[最新版本](https://docs.depositar.io/zh_TW/stable/changelog.html#v6-4-6-2021-09-10)中，
我們改以 XLoader 擴充套件處理結構化資料。
由於 XLoader 預設不進行上述的欄位類型判定，現在您提及的 CSV 應已正常顯示。

僅作以上更新，謝謝！

PS.

1. 目前僅就您提及的 CSV 重新處理。其他已上傳檔案若遇到相同問題，無需重新上傳，僅需到該檔案的管理頁面 (點選頁面右上按鈕)，選取上方 DataStore 頁籤，在接下來的頁面按下「上傳至 DataStore」按鈕即可。該頁面亦會呈現結構化資料的處理結果。
2. 新上傳的檔案應不會再遇到上傳中斷的問題。
3. XLoader 的說明文件中關於欄位類型判定的說明：https://github.com/ckan/ckanext-xloader#caveat---column-types

**Comment by chengh42** [comment]
非常謝謝！
