### ISSUE TITLE
新註冊的使用者，建立Dataset後無法加入相關主題

### ISSUE THREAD

**Issue by allycat** [depositar/ckanext-data-depositario#6]
### 預期行為
剛新註冊的使用者，建立專案／資料集後，預期可以在主題頁面看到下拉選單

### 實際行為
新使用者操作後，主題選單下無主題可選。
若用超級管理者身份登入後，則可看到下拉的主題選單，預計是權限的問題。

**Comment by u10313335** [comment]
確認為權限問題。預計工作為：

- [ ] 新使用者：建立時自動加入至所有主題為成員 (需要修改程式邏輯)
- [ ] 既有使用者：將其加入所有主題 (撰寫 script 達成)

**Comment by u10313335** [comment]
新使用者部分於 v6.3.5 完成，既有使用者於今日以 script 完成。
