### ISSUE TITLE
<class 'geoalchemy2.functions.ST_AsEWKB'> construct has no default compilation handler.

### ISSUE THREAD

**Issue by homegis** [depositar/ckanext-data-depositario#9]
I have installed depositario by following the DOC(https://docs.depositar.io/en/6.3.5/maintaining/installing/install-from-source.html) by several times. When I created spatial fields for a dataset and allways got the same problem:

> Spatial: Error: <class 'geoalchemy2.functions.ST_AsEWKB'> construct has no default compilation handler.

**Comment by u10313335** [comment]
Hi @homegis, may I have your OS version and the output of `pip freeze`?

**Comment by homegis** [comment]
@u10313335 thanks a lot. I have found the problem, the version of GeoAlchemy2 is 0.3, is not compatible with SQLAlchemy(0.9). So I changed to 0.3, it works.

**Comment by u10313335** [comment]
Thanks @homegis. And, the author of upstream repository also fixed this issue (https://github.com/ckan/ckanext-spatial/pull/215). I will merge that fix in the near future.
